### PR TITLE
Use switch statements when handling ops

### PR DESCRIPTION
**Pull request by AnthonyFuller**
Before this PR, the SMP would evaluate actions (and technically conditions) in a set order. This PR resolves the long-time TODO to refactor it to a switch statement. It now respects ordering. Tests have been added.

### CODE REVIEW

**Review by RDIL — APPROVED** [review]
I hate this code with every fiber of my being. Rewrite time?

**Comment by AnthonyFuller** [comment]
As long as timers are properly implemented.

**Review by grappigegovert — COMMENTED** [review]
It's not necessary to have the switch statement for conditions, because you can't have more than one condition in a single object, you need `$and` or `$or` to combine multiple.

Looks good otherwise.

**Comment by AnthonyFuller** [comment]
Yeah that's fair, I just searched for `hasOwnProperty` and refactored it. This will be _marginally_ faster anyway.

**Pull request merged**
