### PR TITLE
Support actions with constants

### PR DESCRIPTION
**Pull request by grappigegovert**
Actions can now reference constants, like for example in this bit of the himmelstein sniper contract:
```
"$inc": [
  "TotalScore",
  "$.Score_Kill_Bodyshot"
]
```
where `Score_Kill_Bodyshot` is the name of a constant

### CODE REVIEW

**Review by RDIL — APPROVED** [review]
🤦

**Comment by RDIL** [comment]
apparently it was already there, just needed to be merged? idk what's going on

**Comment by AnthonyFuller** [comment]
image
I added it ~2 weeks ago. Branch was out of date.

**Comment by RDIL** [comment]
Merged since it adds a test.

**Comment by grappigegovert** [comment]
> I added it ~2 weeks ago. Branch was out of date.
Sorry for the confusion, the testing I did seemed to point to an issue with constants, which nicely coincided with my outdated local copy.

**Comment by AnthonyFuller** [comment]
Yeah, it's no problem. It would've caused issues as the value would've been turned into a string and the constant name would just get appended on the end, a la:
```
"TotalScore":"0Score_Kill_HeadshotNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNScore_Kill_MovingNaNNaNNaNScore_Kill_HeadshotNaNNaNNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNScore_Kill_MovingNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNScore_Kill_MovingNaNNaNNaNScore_BodyHiddenNaNScore_Kill_HeadshotNaNNaNNaNScore_Kill_HeadshotNaNNaNNaN"
```

**Pull request merged**
